### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chenxiaoting-0613** [XingBowen714/DARER#1]
(xiaoting) test@test-X785-G30:~/liuluyao/xiaoting/DARER-main$ python -u main.py -lr 1e-3 -l2 1e-8 -dd dataset/mastodon -hd 128 -mc 2 -dr 0.2 -sn 3
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from nn import TaggingAgent
  File "/home/test/liuluyao/xiaoting/DARER-main/nn/__init__.py", line 1, in <module>
    from nn.model import TaggingAgent
  File "/home/test/liuluyao/xiaoting/DARER-main/nn/model.py", line 7, in <module>
    from nn.encode import BiGraphEncoder
  File "/home/test/liuluyao/xiaoting/DARER-main/nn/encode.py", line 2, in <module>
    from torch_geometric.nn import RGCNConv
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/test/anaconda3/envs/xiaoting/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by XingBowen714** [comment]
It seems that the error is caused by your environment. I didn't encounter this kind of problem. Maybe you can fix this by creating a new virtual env and then installing the needed packages.

**Comment by chenxiaoting-0613** [comment]
Hello, I reported an error here when I reproduced. Is it caused by the lack of files?

loading word vectors...
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    args.linear_decoder, args.pretrained_model, args.rgcn_num_base, args.stack_num, args.margin_coefficient)
  File "F:\fuxian\DARER-main\pre-trained language model\nn\model.py", line 61, in __init__
    dat_fname='{0}_{1}_embedding_matrix.dat'.format(str(300), ds_n))
  File "F:\fuxian\DARER-main\pre-trained language model\utils\load.py", line 165, in build_embedding_matrix
    word_vec = load_word_vec(fname, word2idx=word2idx, embed_dim=embed_dim)
  File "F:\fuxian\DARER-main\pre-trained language model\utils\load.py", line 147, in load_word_vec
    fin = open(path, 'r', encoding='utf-8', newline='\n', errors='ignore')
FileNotFoundError: [Errno 2] No such file or directory: '/home/bxing/Data/supports/glove.840B.300d.txt'
